PMPHAnKQVJA]pLVKQCLaGLKAW.@AWGVMTPMKJsLMWTAVWKBPMIAGEVV]PEHAWQJPKH@IAHK@MAWHMOAPLVAE@WSAERMJCWPKVMAWKBPLALAEVP
mJPLAWP]HAKBmHEM]EVEENEPLAIQWMGAGLKAWSMPLSEVIPLEJ@JKWPEHCME
.TVKITPvAPVK	MJWTMVA@KVGLAWPVEHEVVEJCAIAJPHQWLWPVMJCWCAJPHAVL]PLIWLEVIKJMQIIAHK@MAWSEVIJKWPEHCMGQJ@AVPKJAWWKQHBQHIEHAEJ@BAIEHARKGEHWVABHAGPMRAEJ@LAEVPBAHPIKK@.GKRAVeVPtVKITPeRMFVEJPPETAWPV]KBWKQJ@SERAWMJPAVSKRAJSMPLCKH@AJHMCLPWAPECEMJWPEFEGO@VKTKBEJAPLAVAEH@VAEIHMOAHEJ@WGETA
iK@AVJ]APPMIAHAWW@AWMCJSMPLEPKQGLKBRMJPECAAHACEJGA
.WB\WKBPKVGLAWPVEHWSAHHWCAJPHATAVGQWWMKJPETWWQFPHAEIFMAJPFEGOCVKQJ@WKQJ@W@MWPEJPGLMIAW.RKGEHWIEHAEJ@BAIEHARKGEHLEVIKJMAWSEVIEJ@JKWPEHCMGA\TVAWWMRAEJ@AIKPMRA.RKGEHWwPVQGPQVA@KVGLAWPVEHTKTPVEGOSMPLEVMGLMJPVKEJ@CAJPHAKQPVKBAEPQVMJCIAHK@MGIEHAEJ@BAIEHARKGEHWPLVKQCLKQP.OA]SKV@WKVGLAWPVEHVAPVKJKWPEHCMGRMJPECAGHEWWMGEHWKQHBQHGMJAIEPMGLEVIKJMQIMJ@MEJGHEWWMGEHSKVH@IQWMGmHEM]EVEENEwtfAIKPMRARMFAW.GK@AjEIAuQKrE@MW.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]mHEM]EVEENE	vAIAIFAVMJCwtfEHEWQFVELIEJ]EIXmWEMCJEJMmHEM]EVEENEwQTAVlMPWKBwtfXEJ@WwKJCW
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVu.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	CAJPHASERAWy.WKBPWPVMJCWGEVAWWPLAEMV.KKKKKKK.LEVIKJMQISLMWTAVWMMMMM.RAVWA	aGLKA@iAIKVMAWy.mJPLAUQMAPKBPLALAEVP.pMIAWCAJPHAAIFVEGA.wPKVMAWQJBKH@JARAVPKTEVP.eLEVIKJMKQWWTEGA.gLKVQW	pMIAHAWW`EJGAy.ELLLLLLKKKKK.iAHK@MAWPLEPJARAVBE@A.mJAGLKAWPLA]VAVATHE]A@.fVM@CA	lAEVPBAHPvABHAGPMKJy.KKKKKKMMMMMMM.nKQVJA]PLVKQCLAGLKAWKBPLATEWP.mJIQWMGIAIKVMAWGEWP.KQPVK	bE@MJChMCLPy.LEVIKJMAWHMJCAVWKBPH]MMMMM.KKKKKK.eCAJPHAWMCLEPMIAHAWWCKK@F]A.gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI.gKT]VMCLPÊçeOPMWmJG
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
