PMPHAmHHQWMKJEV]vKE@W.@AWGVMTPMKJmJESKVH@SLAVAVAEHMP]FHQVWMJPKMHHQWMKJPLAWPVAAPWEVAEHMRASMPLRMFVEJPE@RAJPQVAW
mJWTMVA@F]PLAPLVMHHMJCAWGETE@AWKBE@MCMPEHVAEHI
.TVKITPaJAVCAPMGW]JPLSERAFAEPVAPVK	BQPQVMWPMGRMFAW@VMRMJCFEWWHMJAW@]JEIMGAHAGPVKJMGAHAIAJPWMIIAVWMRAWKQJ@WGETAIEHAEJ@BAIEHARKGEHSMPLETHE]BQHEJ@E@RAJPQVKQWPKJA.GKRAVeVPtVKITPeWHAAO`AhKVAEJWTAA@MJCPLVKQCLEJAKJ	HMPBQPQVMWPMGGMP]WGETARMFVEJPGKHKVW@]JEIMGIKPMKJFHQVCHKSMJCGMP]HMCLPWQHPVE	IK@AVJEJ@GETPMREPMJC.WB\AJCMJAVARWAHAGPVKJMGSLKKWLAWBQPQVMWPMGGMP]EIFMAJGA@MCMPEHFAATW.RKGEHWIEHAEJ@BAIEHARKGEHWTHE]BQHE@RAJPQVKQWPKJAWHE]AVA@LEVIKJMAW.RKGEHWwPVQGPQVA@W]JPLSERAPVEGOSMPLEJAJAVCAPMGMJPVKEJ@EGKITAHHMJCKQPVKBAEPQVMJCWKIA@VKTWEJ@IAHK@MGIEHAEJ@BAIEHARKGEHW.OA]SKV@WW]JPLSERAVAPVKSERABQPQVMWPMGAHAGPVKJMGE@RAJPQVAJAKJG]FAVTQJOGMJAIEPMGWKQJ@PVEGOMIIAVWMRA@AHKVAEJVAE@]THE]AVKJA.GK@AjEIAmJRMWMFHAiEJ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]vAE@]tHE]AVkJA	eHH`AhKVAEJwGAJAW
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVm.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	JAKJTQHWAy.SKKKKK.^^^^^^.RAVWA∆§∑`MCMPEH`VMRAy.pLVKQCLWPVAAPWKBHMCLPSLAAHWWTMJPLAPEHA.mJ@VAEIWSAVM@ASLAVAPMIAGEJ∆§ΩPTVAREMH.MMMMMMKKKKKKK.gLKVQW∆§∑aHAGPVMGaWGETAy.KKKK.mHHQWMKJEV]VKE@WSLAVASA@EVAPKBH].mJPLACHKSKBPLAWGVAAJWSAPKQGLPLAWO].^^^^^^LLLLLL.SKKKKK.fVM@CA	g]FAVrMWMKJWy.mJPLALQIKBPLAJMCLPAGLKAWKBPLATEWP.vM@MJCPLVKQCLSKVH@WPKCAPLAVSAHEWP.WLLLLLLLL.KQPVK	bE@APKbQPQVAy.gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI.gKT]VMCLPÊçeOPMWmJG
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
