PMPHAiAHK@MAWKBgVMIWKJhKRAiAHK@MgMJPEiAVEL.@AWGVMTPMKJmJESKVH@TEMJPA@SMPLWLE@AWKBVA@HKRASLMWTAVWWKBPH]HMOAPLAKGAEJWCAJPHAAIFVEGA
mJWTMVA@F]PLAWP]HAKBwLMJPEcMWQHPLMWPVEGOSAERAWEPEHAKBTEWWMKJEJ@]AEVJMJC
.TVKITPtKT	MJBQWA@FEHHE@SMPLWKBPEGKQWPMGCQMPEVCAJPHATMEJKIAHK@MAWWKKPLMJCWPVMJCWEJ@ELAEVPBAHPEPIKWTLAVAAJVMGLA@SMPLHQWLLEVIKJMAWIEHAEJ@BAIEHARKGEH@QAPPAJ@AVEJ@AIKPMRA.GKRAVeVPtVKITPeVKIEJPMGWQJWAPKRAVEWAVAJAFAEGLSEVIPKJAWWKBPTMJOEJ@GVMIWKJLQAWIK@AVJEJ@@VAEI]EAWPLAPMGWGETPQVMJCEWAJWAKBHKJCMJCEJ@HKRA.WB\WKBPKGAEJSERAWCAJPHAFVAA^A@MWPEJPWAECQHHGEHHWWQFPHALAEVPFAEPW.RKGEHWIEHAEJ@BAIEHARKGEH@QAPPAJ@AVEJ@AIKPMRALEVIKJMKQWFHAJ@.RKGEHWwPVQGPQVA@TKTFEHHE@PVEGOSMPLCAJPHAMJPVKEJ@LAEVPBAHPKQPVKMJGHQ@MJCLEVIKJMKQWRKGEH@QAPSMPLWKBPMJWPVQIAJPEHFVAEOW.OA]SKV@WTKTFEHHE@VKIEJPMGEGKQWPMGMJ@KJAWMEJTKT@QAPWKBPRMFAWHKRAAIKPMKJGMJAIEPMGWLMJPECMWQHWP]HA.GK@AjEIAiAIKMVWKBEcAMWLE.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]gmjpeiavelneifq	wLMJPEcMWQH
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVi.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKy.RAVWAy.mJPLACHKSKBWQJWAPWAIFVEGA.gKHKVW@EJGALAEVPWMJPAVHEGA.cAJPHASLMWTAVWGVMIWKJPM@A.GLKVQWy.KKKKKK.MMMMMMM.hKRAWIAHK@]PAJ@AVEJ@SM@A.FVM@CAy.mJPLAWMHAJGASABMJ@KQVSE].aGLKMJC@VAEIWJMCLPPQVJWPK@E].ELLLLLL.WLLLLLL.KQPVKy.mJPLASERAWKQVLAEVPWVAWM@A.wKBPH]WTKOAJF]PLAWAEWM@A.gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI.gKT]VMCLPÊçeOPMWmJG
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
