PMPHAvAWKJEJPaGLKAWaGKWVAWKJEJPAW.@AWGVMTPMKJ`MRAMJPKPLAGLEKWSLAVAAGLKAWKBPLATEWPWLETAPLATVAWAJP
mJWTMVA@F]PLAWP]HAKBmIECMJA`VECKJWPLMWPVEGOVAWKJEPAWSMPLPLALAEVPWBAVRAJPFAEP
.TVKITPaJAVCAPMGVKGOFAEPTKSAVBQHAHAGPVMGCQMPEVVMBBWMJPAJWA@VQITEPPAVJW@]JEIMGVL]PLIEJPLAIMGRMFAFKH@IEHARKGEH@VMRMJCAJAVC].GKRAVeVPtVKITPeBQPQVMWPMGGMP]WGETASMPLPKSAVMJCWO]WGVETAVWJAKJHMCLPWVABHAGPMJCKBBSAPWPVAAPW@]JEIMGAJAVC]EJ@IKRAIAJPFKH@EJ@RMFVEJPGKHKVWEPIKWTLAVMGEJ@GMJAIEPMGWP]HA.WB\PLQJ@AVKQW@VQIGVEWLAWAGLKMJCCQMPEVBAA@FEGOAHAGPVMGLQIGVKS@GLAAVMJC.RKGEHWIEHARKGEHMJPAJWAEJ@TKSAVBQHSMPLGKIIEJ@MJCTVAWAJGA.RKGEHWwPVQGPQVA@VKGOEJPLAIPVEGOSMPLWPVKJCMJPVKEJ@@]JEIMGKQPVKMJGHQ@MJCWKIAA\THKWMRA@VKTWSMPLTKSAVBQHIEHARKGEH.OA]SKV@WVKGOEHPAVJEPMRAMJ@MAEJPLAIMGAJAVCAPMGmIECMJA`VECKJWMJWTMVEPMKJEHGMJAIEPMGRMFAWATMG.GK@AjEIAvE]QAHE.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]mIECMJA`VECKJW	fAHMARAV
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVv.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
