PMPHAbVECIAJPWKBwAVAJMP]bVECIAJoAPAJPVEIEJ.@AWGVMTPMKJmJE@EJGAKBGVAEPMKJEJ@VABHAGPMKJEIAHK@]SAERAWPLVKQCLPLALAEVP
mJWTMVA@F]PLAPMIAHAWWAGLKAWKBWLKHESEPMJPLAWP]HAKBeHfEVOEL
.TVKITPmJWTMVA@F]PVE@MPMKJEHWLKHESEPIAHK@MAWFHAJ@A@SMPLIK@AVJTKTAHAIAJPWCAJPHATAVGQWWMKJWKQHBQHWPVMJCWEJ@@AATVAWKJEJPIEHARKGEHWAVAJAEJ@QTHMBPMJCEPIKWTLAVA.GKRAVeVPtVKITPeWAVAJAI]WPMGEHHEJ@WGETASMPLEIK@AVJPSMWPCHKSMJCAHAIAJPWMJPLAWO]WKBPTEWPAHGKHKVWEJ@EBQWMKJKBPVE@MPMKJEHEJ@BQPQVMWPMGIKPMBWGVAEPMJCETAEGABQH]APGKJPAITKVEV]RMFA.WB\CAJPHASMJ@GLMIAWWKBPSLMWTAVMJCSMJ@W@MWPEJPAGLKAWKBPVE@MPMKJEHMJWPVQIAJPWEIFMAJPJEPQVAWKQJ@W.RKGEHWIEHARKGEHLAEVPBAHPEJ@WKKPLMJCSMPLEPVE@MPMKJEH]APIK@AVJPSMWP.RKGEHWwPVQGPQVA@TKTPVEGOSMPLEWIKKPLMJPVKEJ@VABHAGPMRAKQPVKBAEPQVMJCWKQHBQHIEHARKGEHLEVIKJMAWEJ@CAJPHAMJWPVQIAJPEH@VKTW.OA]SKV@WTKTPVE@MPMKJEHSKVH@IQWMGBQWMKJWLKHESEPWAVAJAQTHMBPMJCWKQHBQHGKJPAITKVEV]TAEGABQHGMJAIEPMGWKQJ@PVEGORMFAW.GK@AjEIAbVEJOAJWPAMJ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]eHfEVOELwLKHESEP	eHFQIwlkhesephejcmpejtKTQHAViEHArAVWMKJXelIE@e@MFiEWVM]E@LoEJCbQE@
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVb.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKSLMWTAVy.KKKKK.RAVWA	aGLKAWKBpVE@MPMKJy.`EHEIEHQJEJLEPMPAVTEQP.wQEVEIAV@QNMSEIAJ]EPQ.hEJCMPPAIEVEIWMJEVHAIFQP.oAPAJEJCEJ@EPEJCVEWETAJQL.GLKVQW	lEVIKJ]KBtAEGAy.EEEE.MMMMMM.FVM@CA	gAHAWPMEH`VMBPy.wQEVEIEHEIFMWMOEJEHEI.`MWAPMETJEBEWVEWEIAJ@EHEI.KQPVK	wAVAJMP]bE@Ay.KKKKK.eLLLLLLLL.gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI.gKT]VMCLPÊçeOPMWmJG
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
