C^C[R
fVE^DrT_Xï‚ï˜î¾îµïï†î½ï„=SRDTE^GC^XY
fVE^DERDXYVCRDC_EXBP_C_RY^P_CVZR[XSNXQTR[RUEVC^XYVYSBY^CNc_RT^CNSVYTRDV[XYP=GEXZGC
bG[^QC^YPz^SS[RrVDCREY^YDG^ERSZR[XSNCEVS^C^XYV[^YDCEBZRYCDU[RYS@^C_ZXSREYURVCD]XNQB[VYSTR[RUEVCXENVZU^VYTRE^T_GRETBDD^XYPRYC[RDCE^YPD@VEZVYS^YA^C^YPZV[RVYSQRZV[RAXTV[@^C_TR[RUEVCXENCXYR=TXAREvECgEXZGC
qBCBE^DC^TT^CNDTVGR@^C_VU[RYSXQCEVS^C^XYV[VYSZXSREYVET_^CRTCBERA^UEVYCY^P_CZVE\RCDTRYR@VEZPX[SRY[^P_CD[^AR[NVYSSNYVZ^TVCZXDG_RERYRXYVTTRYCD=DQO
T^CNVZU^VYTRS^DCVYCQRDC^ART_VCCREE_NC_Z^TGRETBDD^XYPRYC[RUERRMRDBUC[RTEX@SYX^DR=AXTV[D
ZV[RVYSQRZV[RAXTV[D_VEZXY^XBDU[RYS@VEZVYSTR[RUEVCXENCEVS^C^XYV[VYSZXSREYQBD^XY=AXTV[DdCEBTCBERS
GXGDCRGCEVT\@^C_PXXS^YCEXVYSY^TRXBCEX^YT[BS^YPDXZRSEXGD@^C_ZR[XS^TQRZV[RAXTV[=\RN@XESD
@XE[SZBD^TZ^SS[RRVDCREYGXGQBD^XYTR[RUEVCXENDXBYSCEVT\QRDC^ARCEVS^C^XYZXSREY^YDG^EVC^XYMV^Y=TXSRyVZR
fVE^D=UGZ
=PRYER~YGBC
=GEXZGC~YGBC
cEVT\^YDG^ERSUNmV^YïïŽî³ïî±ï…î½î±ï‚î¿ïïî³ïŽî½ï˜bDRD^Z^[VEZBD^TV[A^URZXXSDCN[RPRYER^YDCEBZRYCD=[RCCRE
f=^YT[BSRaXTV[
qV[DR=VGGaRED^XY
A=SBEVC^XY
==[NE^TD
l^YCEXPRYC[RV@V\RY^YPj=AX^TRï‚î¿ïïî³ïŽî½ï˜Õ·‘î½î±ïŸïŽî²î±ïî³îµî³ïŸ=AX^TRî¶î½î´î³ï…ïî¿î½ïžÕ·‘î¶ï†ïšïžïï›î²ïŽî±ï=XXXXXXX=lAREDRÕ·¤tR[RUEVC^XYgB[DRj=ï”î±ïïî²ïï†î¿î½îµï‚ïžïî³ïŽî½ï˜=ïï›î²ïŽî±ïÕ·‘ï†ïî²ïî³î²ï„ïî¶ïï=î²ïŽî´î³î±ïî²ïžî±ïŸïïî³îµî³ïŸî½ïï„ïï†ïŽ=î½ïïïïï=lT_XEBDÕ·¤VEZXY^XBD}XNj=î²î¿ï„î½îµî¾ïî³ïŽî½ï˜ïï‚ï˜ïšî¶î½ïî³ï”î¶îµ=^^^^^^^=ïŽî½ï˜ï„ïŽî½ï˜î³î´î³ïî³îµî³î¿ïŸ=lUE^SPRbY^CNrT_Xj=ï‚î¿ïî¶î½î´î³ï…ïî¿î½ïžï»î±î³ïîµî½=ïî³ï™î½î¿ï€ïî³ï‡î°ïŸî½ïžïî³î²ïŽî¶î½ïî³î³î½î³=ïïïïïî°î°=lXBCEXfVE^DrT_Xj=@_^DGREï‚î¿ïïî³ïŽî½ï˜Õ·‘ï‚î¿ïïî³ï”î²î³=î½ïî²ï†î±ïÕ·‘î½î¿ïšï˜î±ï=XXXXXVVVVV==tERVCRSUNvcg[VNRE=_CCGD@@@VCG[VNRETXZ==tXGNE^P_Cõžv\C^D~YT