PMPHA~EBMVK@AeHEFEJ^E~EBMVK@AeHEFEJ^E.@AWGVMTPMKJ~KVVKWIEWOLM@AWELAEVPBQHHKBHMCLP
mJPLAWP]HAKBaHMEWjELQIPLMWPVEGOHMBPWWTMVMPWSMPLMPWWAVAJAFAEQP]EJ@TQVARKGEHW
.TVKITPmJWTMVEPMKJEHEJ@QTHMBPMJCPVEGOCAJPHAEGKQWPMGCQMPEVWKKPLMJCTMEJKWAVAJAWPVMJCWSEVILEVIKJMAWWTMVMPQEHEJ@LAEVPBAHPEPIKWTLAVA]KQPLBQHIEHARKGEHEJCAHMGEJ@TQVAPKJA.GKRAVeVPtVKITPeVE@MEJPHEJ@WGETAFEPLA@MJCKH@AJHMCLPEIENAWPMGWETTLMVAWO]APLAVAEHCHKSWQVVKQJ@MJCETAEGABQHREHHA]IK@AVJEJ@@VAEIHMOABQHHKBLKTAEJ@WAVAJMP].WB\CAJPHASMJ@VQWPHAWKBPGLMIA@MWPEJPGLKMVLQIPVEJUQMHVMRAVBHKS.RKGEHW]KQJCIEHARKGEHEJCAHMGPKJATQVAEJ@LAEVPBAHP@AHMRAV]WTMVMPQEHVAWKJEJGA.RKGEHWwPVQGPQVA@TKTWPATPVEGOSMPLCKK@MJPVKEJ@JMGAKQPVKMJGHQ@MJCWKIA@VKTWSMPLIAHK@MGIEHARKGEH.OA]SKV@WMJWTMVEPMKJEHQTHMBPMJCEGKQWPMGCKWTAHWTMVMPQEHWAVAJAEJCAHMG]KQPLBQHaHMEWjELQIgLEVHMAfQWPKWSKVWLMTIQWMGPVEJUQMHTAEGABQH.GK@AjEIA~KVVK.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]aHMEWjELQI	aHMEWjELQIjAGAWMPKpm@AgLEVHMAfQWPKWJMJKUQAGEJPELAVIKWKTEVE`MKWeHEFEJ^EW
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV~.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
