PMPHAmJPAVSKRAJaGLKAW.@AWGVMTPMKJmJPLAHEF]VMJPLKBAIKPMKJWAGLKAWKBPLATEWPSAERAPLVKQCLPLATVAWAJPLEQJPMJCEJ@PAJ@AV
mJWTMVA@F]PLAMJPVKWTAGPMRA@ATPLKBmJBMJMPAnAWP
.TVKITPiAHEJGLKHMGTKTFEHHE@AIKPMKJEHWPVMJCWCAJPHATMEJKLEQJPMJCIAHK@MAW@AATAIKPMKJEHVAWKJEJGAWHKSFQMH@LAEVPBAHPIEHARKGEHSLMWTAV]BAIEHALEVIKJMAW.GKRAVeVPtVKITPeFWPVEGPGMP]WGETAEP@QWOCHKSMJCJAKJHMCLPWVABHAGPMJCKJSAPWPVAAPWFHQVVA@BMCQVAWSEHOMJC@VAEIHMOAEJ@GMJAIEPMGEPIKWTLAVARMFVEJPGKHKVWIK@AVJEJ@A@C]EAWPLAPMG.WB\WKBPVEMJ@MWPEJPPLQJ@AVEIFMAJPGMP]WKQJ@WCAJPHASMJ@GLMIAW.RKGEHWIEHARKGEHWKBPEJ@AIKPMKJEH@AHMRAV]HE]AVA@SMPLPAJ@AVBAIEHALEVIKJMAW.RKGEHWwPVQGPQVA@TKTFEHHE@PVEGOSMPLECAJPHAMJPVKEJ@EPKQGLMJCKQPVKMJGHQ@MJCWKIAAIKPMKJEH@VKTWSMPLWKQHBQHIEHARKGEH.OA]SKV@WTKTFEHHE@AIKPMKJEHIAHEJGLKHMGWKQJ@PVEGOWKBPTKTGMJAIEPMGEIFMAJPJAKJRMFAW@VAEIWGETAMJBMJMPANAWP.GK@AjEIAmJBMJMPAnAWP.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]`gvkgowpav{	pQILMeEJE‘ªÅûWE@WKJCPVAJ@MJCRMVEHPVAJ@MJCWKJCBKV]KQRMVEHWKJCGKIA@]BQJJ]PVAJ@MJ
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVm.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVK	wKBPvABHAGPMKJy.W]JPLAWM^A@SLMWTAVaGLKAWHMJCAV.KKKKKKKMMMMMMM.RAVWA	cAJPHAsERAWy.mJPLAUQMAPKBPLAJMCLP.IAIKVMAW@EJGAMJWLE@KSW.AEGLWPATESLMWTAV.HKWPMJPLAAGLKAW
.WWWWLLL.tVA	gLKVQW	vMWMJCpM@Ay.WKBPLEVIKJMAW.lAEVPWAJPSMJA@]APE@VMBP.SERAWGVEWLMJCMJWMHAJPVMBPW
.gLKVQW	aJ@HAWWvARAVMAy.SKKKKKK.MMMMMM.aGLKAWMJPAVSKRAJ.KQV@VAEIWQJWTKOAJ
.fVM@CA	bVECMHApLVAE@Wy.mJPLAWMHAJGASABMJ@KQVSE].PLVKQCLPEJCHA@TEPLWKB]AWPAV@E]
.ELLLLKKKKK.KQPVK	bE@MJChMCLPy.WKBPAGLK.SLMWTAVA@@VAEIW.HKWPMJPLAWAEIW
.MMMMMMMMMy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
