PMPHAqJ@AVPLApVKTMGEH|fENKHE|pVKTMGEH.@AWGVMTPMKJ`AAT@VQIFAEP
nQJCHASLMWTAVWGEHH
mJPLAWP]HAKB`nwJEOAwAHAJEcKIA^k^QJEEJ@gEV@MfEJEJGMAJPTQHWAIAAPWBQPQVAVL]PLI
.TVKITPvACCEAPKJFAEPSMPLPVKTMGEHW]JPLTE@WLAER]FEWWHMJA@]JEIMGhEPMJTAVGQWWMKJHKKTL]TJKPMGW]JGKTEPA@VL]PLIWQIIAV]TEVP]IKK@MJGHQ@AWHE]AVA@IEHAEJ@BAIEHAAJAVCAPMGRKGEHWEJ@KGGEWMKJEHWTKOAJTLVEWAW.GKRAVeVPtVKITPrMFVEJPJAKJ	HMPBQPQVMWPMGPVKTMGEHNQJCHAEPJMCLPCHKSMJCEHMAJBHKVEWHAAOLKHKCVETLMGTVKNAGPMKJWWLMIIAVMJCPLVKQCLHAERAWEFWPVEGPHMCLPPVEMHWMJPAVWAGPMJC@MCMPEHVEMJABBAGPMJPAJWAH]WEPQVEPA@GKHKVWRMWQEHH]WPVMOMJCEJ@IK@AVJWGM	BM.WB\NQJCHAEIFMEJGASMPL@MCMPEHCHMPGLAWVL]PLIMGW]JPLTQHWAW@MWPEJPAGLKMJCTAVGQWWMRAWKQJ@WLKHKCVETLMGWLMIIAVABBAGP.RKGEHWIEHAEJ@BAIEHARKGEHWWMJCMJCEJ@WTKOAJSKV@AJAVCAPMGEJ@WHMCLPH]TVKGAWWA@.RKGEHWwPVQGPQVA@TKTWPATPVEGOSMPLCKK@MJPVKEJ@JMGAKQPVKMJGHQ@MJCWKIA@VKTWSMPLIAHK@MGBAIEHARKGEH.OA]SKV@WVACCEAPKJHEPMJTKT@EJGALEHHTKTPVKTMGEHLKQWALMTLKT@EJGAWQIIAVEJPLAITEVP]RMFAWQVFEJHEPMJ@NWJEOAWAHAJECKIA^K^QJEGEV@MF.GK@AjEIA|MJCQ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]`nwJEOA	pEOMwAHAJEcKIA^k^QJEgEV@Mf
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV|.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
